version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: development
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: bundle exec rails s -p 3100 -b '0.0.0.0'
    volumes:
      - ./backend:/app/backend
      - app-bundle:/app/vendor/bundle:cached
    ports:
      - '3100:3100'
    depends_on:
      - db
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME:-root}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-password}

  frontend:
    build: ./frontend
    working_dir: /app/frontend
    command: npx nuxi dev
    volumes:
      - ./frontend:/app/frontend
      - app-module:/app/frontend/node_modules:cached
    ports:
      - '3000:3000'

volumes:
  db-data:
  app-bundle:
  app-module:
